# Generated by Django 4.2.1 on 2023-06-27 22:52

import control_vehicular.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_minima', models.DecimalField(decimal_places=2, help_text='El kilometraje/tiempo mínimo en el que se deben realizar las operaciones.', max_digits=10, verbose_name='Frecuencia mínima')),
                ('final_ciclo', models.DecimalField(decimal_places=2, help_text='El kilometraje/tiempo límite que marca el fin de cada ciclo de mantenimiento.', max_digits=10, verbose_name='Final de ciclo de mantenimiento')),
                ('unidad', models.CharField(choices=[('km', 'KILOMETROS'), ('mi', 'MILLAS'), ('días', 'DIAS')], help_text='La unidad de medida del kilometraje.', max_length=10, verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Hoja de mantenimiento',
                'verbose_name_plural': 'Hojas de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('F', 'F'), ('A1', 'A1'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('D1', 'D1'), ('E', 'E'), ('E1', 'E1')], help_text='El tipo de la licencia (A, B, C, etc.).', max_length=2)),
                ('fecha_de_emision', models.DateField(help_text='La fecha de emisión de la licencia.')),
                ('fecha_de_caducidad', models.DateField(help_text='La fecha de caducidad de la licencia.', validators=[control_vehicular.models.validar_vigencia_licencia])),
                ('puntos', models.PositiveSmallIntegerField(help_text='Puntos vigentes de la licencia.')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('trabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.trabajador')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
            bases=('login.trabajador',),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio_de_fabricacion', models.PositiveIntegerField(help_text='El año de fabricación del vehículo.', validators=[control_vehicular.models.validar_anio_fabricacion], verbose_name='Año de fabricación')),
                ('cilindraje', models.DecimalField(decimal_places=4, help_text='El cilindraje del vehículo.', max_digits=10, verbose_name='Cilindraje')),
                ('color', models.CharField(help_text='El color del vehículo.', max_length=50, verbose_name='Color')),
                ('combustible', models.CharField(choices=[('Gasolina', 'GASOLINA'), ('Diésel', 'DIESEL'), ('Gas', 'GAS'), ('Eléctrico', 'ELECTRICO')], help_text='El tipo de combustible del vehículo.', max_length=30, verbose_name='Combustible')),
                ('condicion', models.CharField(choices=[('Operable', 'OPERABLE'), ('No operable', 'NO_OPERABLE'), ('En mantenimiento', 'EN_MANTENIMIENTO')], help_text='La condición vehicular del vehículo.', max_length=30, verbose_name='Condición vehicular')),
                ('foto_matricula', models.ImageField(blank=True, help_text='La fotografía de la matrícula.', null=True, upload_to='vehiculos', verbose_name='Fotografía de la matrícula')),
                ('foto_vehiculo', models.ImageField(blank=True, help_text='La fotografía del vehículo.', null=True, upload_to='vehiculos', verbose_name='Fotografía del vehículo')),
                ('marca', models.CharField(help_text='La marca del vehículo.', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='El modelo del vehículo.', max_length=50, verbose_name='Modelo')),
                ('numero_de_chasis', models.CharField(help_text='Número de chasis del motor.', max_length=20, unique=True, verbose_name='Número del chasis')),
                ('placa', models.CharField(help_text='La placa del vehículo.', max_length=10, unique=True, validators=[control_vehicular.models.validar_placa_vehicular], verbose_name='Placa')),
                ('tonelaje', models.DecimalField(decimal_places=2, help_text='El tonelaje del vehículo.', max_digits=10, verbose_name='Tonelaje')),
                ('unidad_carburante', models.DecimalField(decimal_places=4, help_text='La unidad de carburante del vehículo.', max_digits=10, verbose_name='Unidad carburante')),
                ('propietario', models.ForeignKey(help_text='El propietario del vehículo.', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='control_vehicular.propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='OperacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(help_text='La tarea a realizar en la operación.', max_length=50, verbose_name='Tarea')),
                ('sistema', models.CharField(help_text='El sistema del vehículo al que pertenece la operación.', max_length=50, verbose_name='Sistema')),
                ('sub_sistema', models.CharField(help_text='El sub-sistema del vehículo al que pertenece la operación.', max_length=50, verbose_name='Sub-sistema')),
                ('frecuencia', models.DecimalField(decimal_places=2, help_text='El kilometraje/tiempo en el que se debe realizar la operación.', max_digits=10, verbose_name='Frecuencia')),
                ('unidad', models.CharField(choices=[('km', 'KILOMETROS'), ('mi', 'MILLAS'), ('días', 'DIAS')], help_text='La unidad de medida del kilometraje.', max_length=10, verbose_name='Unidad')),
                ('hoja_mantenimiento', models.ForeignKey(help_text='Hoja mantenimiento a la que pertenece este mantenimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_de_mantenimiento', to='control_vehicular.hojamantenimiento')),
            ],
            options={
                'verbose_name': 'Operación de mantenimiento',
                'verbose_name_plural': 'Operaciones de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_fabricacion', models.CharField(help_text='El código de fabricación de la llanta.', max_length=50, validators=[control_vehicular.models.validar_codigo_dot], verbose_name='Código de fabricación')),
                ('posicion_respecto_al_vehiculo', models.CharField(choices=[('Derecho delantero', 'DERECHO_DELANTERO'), ('Derecho posterior', 'DERECHO_POSTERIOR'), ('Derecho posterior exterior', 'DERECHO_POSTERIOR_EXTERIOR'), ('Derecho posterior interior', 'DERECHO_POSTERIOR_INTERIOR'), ('Izquierdo delantero', 'IZQUIERDO_DELANTERO'), ('Izquierdo posterior', 'IZQUIERDO_POSTERIOR'), ('Izquierdo posterior exterior', 'IZQUIERDO_POSTERIOR_EXTERIOR'), ('Izquierdo posterior interior', 'IZQUIERDO_POSTERIOR_INTERIOR'), ('Respuesto', 'REPUESTO')], help_text='La posición de la llanta respecto al vehículo.', max_length=50, verbose_name='Posición respecto al vehículo')),
                ('vehiculo', models.ForeignKey(help_text='El vehículo al que pertenece la llanta.', on_delete=django.db.models.deletion.CASCADE, related_name='llantas', to='control_vehicular.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Kilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.DecimalField(decimal_places=2, help_text='El kilometraje recorrido por el vehículo.', max_digits=10, verbose_name='Kilometraje')),
                ('unidad', models.CharField(choices=[('km', 'KILOMETROS'), ('mi', 'MILLAS'), ('días', 'DIAS')], help_text='La unidad de medida del kilometraje.', max_length=10, verbose_name='Unidad')),
                ('fecha', models.DateField(help_text='La fecha en la que se registro X kilometraje.', verbose_name='Fecha')),
                ('vehiculo', models.ForeignKey(help_text='El vehículo al que pertenece el odómetro.', on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_kilometraje', to='control_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Kilometraje',
                'verbose_name_plural': 'Kilometrajes',
            },
        ),
        migrations.AddField(
            model_name='hojamantenimiento',
            name='vehiculo',
            field=models.OneToOneField(help_text='El vehículo al que pertenece la hoja de mantenimiento.', on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo'),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('trabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.trabajador')),
                ('licencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.licencia')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
            bases=('login.trabajador',),
        ),
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_fabricacion', models.CharField(help_text='El código de fabricación de la batería.', max_length=50, validators=[control_vehicular.models.validar_codigo_bateria], verbose_name='Código de fabricación')),
                ('vehiculo', models.ForeignKey(help_text='El vehículo al que pertenece la batería.', on_delete=django.db.models.deletion.CASCADE, related_name='baterias', to='control_vehicular.vehiculo')),
            ],
        ),
    ]
