# Generated by Django 4.2.1 on 2023-05-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_vehicular', '0004_alter_llanta_posicion_respecto_al_vehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='es_profesional',
        ),
    ]
