# Generated by Django 4.2.1 on 2023-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_vehicular', '0005_remove_licencia_es_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencia',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterField(
            model_name='llanta',
            name='posicion_respecto_al_vehiculo',
            field=models.CharField(choices=[('Derecho delantero', 'DERECHO_DELANTERO'), ('Derecho posterior', 'DERECHO_POSTERIOR'), ('Derecho posterior exterior', 'DERECHO_POSTERIOR_EXTERIOR'), ('Derecho posterior interior', 'DERECHO_POSTERIOR_INTERIOR'), ('Izquierdo delantero', 'IZQUIERDO_DELANTERO'), ('Izquierdo posterior', 'IZQUIERDO_POSTERIOR'), ('Izquierdo posterior exterior', 'IZQUIERDO_POSTERIOR_EXTERIOR'), ('Izquierdo posterior interior', 'IZQUIERDO_POSTERIOR_INTERIOR'), ('Respuesto', 'REPUESTO')], max_length=50, verbose_name='Posición respecto al vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('Gasolina', 'GASOLINA'), ('Diésel', 'DIESEL'), ('Gas', 'GAS'), ('Eléctrico', 'ELECTRICO')], max_length=30, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='condicion',
            field=models.CharField(choices=[('Operable', 'OPERABLE'), ('No operable', 'NO_OPERABLE'), ('En mantenimiento', 'EN_MANTENIMIENTO')], max_length=30, verbose_name='Condición vehicular'),
        ),
    ]
