# Generated by Django 4.2.1 on 2023-05-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_vehicular', '0006_alter_licencia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='licencia',
            options={},
        ),
    ]
