# Generated by Django 4.2.1 on 2023-06-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_vehicular', '0008_remove_vehiculo_unidad_carburaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateria',
            name='codigo_de_fabricacion',
            field=models.CharField(help_text='El código de fabricación de la batería.', max_length=50, verbose_name='Código de fabricación'),
        ),
        migrations.AlterField(
            model_name='bateria',
            name='vehiculo',
            field=models.ForeignKey(help_text='El vehículo al que pertenece la batería.', on_delete=django.db.models.deletion.CASCADE, related_name='baterias', to='control_vehicular.vehiculo'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_de_caducidad',
            field=models.DateField(help_text='La fecha de caducidad de la licencia.'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('F', 'F'), ('A1', 'A1'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('D1', 'D1'), ('E', 'E'), ('E1', 'E1')], help_text='El tipo de la licencia (A, B, C, etc.).', max_length=2),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='codigo_de_fabricacion',
            field=models.CharField(help_text='El código de fabricación de la llanta.', max_length=50, verbose_name='Código de fabricación'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='posicion_respecto_al_vehiculo',
            field=models.CharField(choices=[('Derecho delantero', 'DERECHO_DELANTERO'), ('Derecho posterior', 'DERECHO_POSTERIOR'), ('Derecho posterior exterior', 'DERECHO_POSTERIOR_EXTERIOR'), ('Derecho posterior interior', 'DERECHO_POSTERIOR_INTERIOR'), ('Izquierdo delantero', 'IZQUIERDO_DELANTERO'), ('Izquierdo posterior', 'IZQUIERDO_POSTERIOR'), ('Izquierdo posterior exterior', 'IZQUIERDO_POSTERIOR_EXTERIOR'), ('Izquierdo posterior interior', 'IZQUIERDO_POSTERIOR_INTERIOR'), ('Respuesto', 'REPUESTO')], help_text='La posición de la llanta respecto al vehículo.', max_length=50, verbose_name='Posición respecto al vehículo'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='vehiculo',
            field=models.ForeignKey(help_text='El vehículo al que pertenece la llanta.', on_delete=django.db.models.deletion.CASCADE, related_name='llantas', to='control_vehicular.vehiculo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='foto',
            field=models.ImageField(blank=True, help_text='La fotografía de la matrícula.', null=True, upload_to='matriculas', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(help_text='El número de la matrícula.', max_length=50, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='propietario',
            field=models.ForeignKey(help_text='El propietario de la matrícula.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_vehicular.propietario'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='vehiculo',
            field=models.OneToOneField(help_text='El vehículo al que pertenece la matrícula.', on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='control_vehicular.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio_de_fabricacion',
            field=models.PositiveSmallIntegerField(help_text='El año de fabricación del vehículo.', verbose_name='Año de fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindraje',
            field=models.FloatField(help_text='El cilindraje del vehículo.', verbose_name='Cilindraje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(help_text='El color del vehículo.', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('Gasolina', 'GASOLINA'), ('Diésel', 'DIESEL'), ('Gas', 'GAS'), ('Eléctrico', 'ELECTRICO')], help_text='El tipo de combustible del vehículo.', max_length=30, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='condicion',
            field=models.CharField(choices=[('Operable', 'OPERABLE'), ('No operable', 'NO_OPERABLE'), ('En mantenimiento', 'EN_MANTENIMIENTO')], help_text='La condición vehicular del vehículo.', max_length=30, verbose_name='Condición vehicular'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='La fotografía del vehículo.', null=True, upload_to='vehiculos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(help_text='La marca del vehículo.', max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(help_text='El modelo del vehículo.', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(help_text='La placa del vehículo.', max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(default=1, help_text='El propietario del vehículo.', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='control_vehicular.propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tonelaje',
            field=models.FloatField(help_text='El tonelaje del vehículo.', verbose_name='Tonelaje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='unidad_carburante',
            field=models.FloatField(help_text='La unidad de carburante del vehículo.', verbose_name='Unidad carburante'),
        ),
    ]
