# Generated by Django 4.2.1 on 2023-05-14 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=10, verbose_name='Cédula')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nivel_educacion', models.CharField(choices=[('GENERAL_BASICA', 'GENERAL_BASICA'), ('BACHILLERATO', 'BACHILLERATO'), ('SUPERIOR', 'SUPERIOR')], max_length=30, verbose_name='Nivel de educación')),
                ('estado_civil', models.CharField(choices=[('CASADO', 'CASADO'), ('DIVORCIADO', 'DIVORCIADO'), ('SOLTERO', 'SOLTERO'), ('UNION_LIBRE', 'UNION_LIBRE'), ('VIUDO', 'VIUDO')], max_length=20, verbose_name='Estado Civil')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotografía')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
