# Generated by Django 4.2.1 on 2023-06-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(help_text='Nombres de la persona.', max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Apellidos de la persona.', max_length=150, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='Cédula de la persona.', max_length=10, validators=[login.models.validar_cedula], verbose_name='Cédula')),
                ('email', models.EmailField(help_text='Email de la persona.', max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(help_text='Teléfono de la persona.', max_length=15, validators=[login.models.validar_numero_de_telefono], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección de la persona.', verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento de la persona.', validators=[login.models.validar_fecha_de_nacimiento], verbose_name='Fecha de nacimiento')),
                ('nivel_educacion', models.CharField(choices=[('GENERAL_BASICA', 'General Básica'), ('BACHILLERATO', 'Bachillerato'), ('SUPERIOR', 'Superior')], help_text='Nivel de educación de la persona.', max_length=30, verbose_name='Nivel de educación')),
                ('estado_civil', models.CharField(choices=[('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('SOLTERO', 'Soltero'), ('UNION_LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo')], help_text='Estado civil de la persona.', max_length=20, verbose_name='Estado Civil')),
                ('fotografia', models.ImageField(blank=True, help_text='Fotografía opcional de la persona.', null=True, upload_to='', verbose_name='Fotografía')),
                ('user', models.OneToOneField(help_text='Relación uno a uno con el modelo User de Django.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
