# Generated by Django 4.2.1 on 2023-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Soltero', 'Soltero'), ('Unión Libre', 'Unión Libre'), ('Viudo', 'Viudo')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_educacion',
            field=models.CharField(choices=[('General Básica', 'General Básica'), ('Bachillerato', 'Bachillerato'), ('Superior', 'Superior')], max_length=30, verbose_name='Nivel de educación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
    ]
