# Generated by Django 4.2.1 on 2023-05-14 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_alter_usuario_apellidos_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Persona',
        ),
    ]
