# Generated by Django 4.2.1 on 2023-05-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_usuario_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('SOLTERO', 'Soltero'), ('UNION_LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nivel_educacion',
            field=models.CharField(choices=[('GENERAL_BASICA', 'General Básica'), ('BACHILLERATO', 'Bachillerato'), ('SUPERIOR', 'Superior')], max_length=30, verbose_name='Nivel de educación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
