# Generated by Django 4.2.1 on 2023-05-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_persona_email_alter_persona_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
    ]
