# Generated by Django 4.2.1 on 2023-05-20 05:27

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_persona_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, validators=[login.models.validar_cedula], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'CASADO'), ('Divorciado', 'DIVORCIADO'), ('Soltero', 'SOLTERO'), ('Unión Libre', 'UNION_LIBRE'), ('Viudo', 'VIUDO')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(validators=[login.models.validar_fecha_de_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nivel_educacion',
            field=models.CharField(choices=[('General Básica', 'GENERAL_BASICA'), ('Bachillerato', 'BACHILLERATO'), ('Superior', 'SUPERIOR')], max_length=30, verbose_name='Nivel de educación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=15, validators=[login.models.validar_numero_de_telefono], verbose_name='Teléfono'),
        ),
    ]
