# Generated by Django 4.2.1 on 2023-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_persona_cedula_alter_persona_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('SOLTERO', 'Soltero'), ('UNION_LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nivel_educacion',
            field=models.CharField(choices=[('GENERAL_BASICA', 'General Básica'), ('BACHILLERATO', 'Bachillerato'), ('SUPERIOR', 'Superior')], max_length=30, verbose_name='Nivel de educación'),
        ),
    ]
