# Generated by Django 4.2.1 on 2023-06-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_alter_persona_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(help_text='Apellidos de la persona.', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(help_text='Cédula de la persona.', max_length=10, validators=[login.models.validar_cedula], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección de la persona.', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(help_text='Email de la persona.', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('SOLTERO', 'Soltero'), ('UNION_LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo')], help_text='Estado civil de la persona.', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Fecha de nacimiento de la persona.', validators=[login.models.validar_fecha_de_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='Fotografía opcional de la persona.', null=True, upload_to='', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nivel_educacion',
            field=models.CharField(choices=[('GENERAL_BASICA', 'General Básica'), ('BACHILLERATO', 'Bachillerato'), ('SUPERIOR', 'Superior')], help_text='Nivel de educación de la persona.', max_length=30, verbose_name='Nivel de educación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(help_text='Nombres de la persona.', max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(help_text='Teléfono de la persona.', max_length=15, validators=[login.models.validar_numero_de_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(help_text='Relación uno a uno con el modelo User de Django.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
