# Generated by Django 4.2.1 on 2023-08-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now=True, help_text='Fecha de emisión de la orden de trabajo', verbose_name='Fecha de emisión')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo conservativo', 'PREVENTIVO_CONSERVATIVO'), ('Preventivo predictivo', 'PREVENTIVO_PREDICTIVO'), ('Correctivo', 'CORRECTIVO'), ('Restaurativo', 'RESTAURATIVO')], help_text='Tipo de mantenimiento a realizar', max_length=30, verbose_name='Tipo de mantenimiento')),
                ('tipo_trabajo', models.TextField(help_text='Descripción del trabajo a realizar', verbose_name='Observaciones')),
                ('cumplimiento', models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Cumplido', 'CUMPLIDO')], help_text='Estado de cumplimiento de la orden de trabajo', max_length=20, verbose_name='Cumplimiento')),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo del mantenimiento')),
                ('responsable', models.ForeignKey(help_text='Responsable de emitir la orden de trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo_responsables', to='usuarios.perfilusuario')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo asociado con la orden de trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo_vehiculos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
            },
        ),
    ]
