# Generated by Django 4.2.1 on 2023-05-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_vehicular', '0007_alter_conductor_options_alter_licencia_options'),
        ('login', '0006_alter_persona_cedula_alter_persona_estado_civil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.persona')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('login.persona',),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.persona')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
            bases=('login.persona',),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Restaurativo', 'Restaurativo')], max_length=20)),
                ('tipo_trabajo', models.TextField()),
                ('cumplimiento', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cumplido', 'Cumplido')], max_length=20)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.responsable')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='OrdenMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now=True)),
                ('itineario', models.TextField()),
                ('detalle_comision', models.TextField()),
                ('fecha_retorno', models.DateField()),
                ('km_retorno', models.IntegerField()),
                ('km_actual', models.IntegerField()),
                ('cumplimiento', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de movimiento',
                'verbose_name_plural': 'Órdenes de movimiento',
            },
        ),
    ]
