# Generated by Django 4.2.1 on 2023-06-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('control_vehicular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaOrdenMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje_salida', models.IntegerField(help_text='Kilometraje del vehículo al momento de la salida')),
                ('fecha_de_emision_orden', models.DateField(auto_now=True, help_text='Fecha de emisión de la orden de movimiento')),
                ('fecha_salida_vehiculo', models.DateField(help_text='Fecha de salida del vehículo')),
                ('itinerario', models.TextField(help_text='Itinerario o viaje')),
                ('detalle_comision', models.TextField(help_text='Detalle de la comisión')),
                ('conductor', models.ForeignKey(help_text='El conductor que va a conducir el vehículo de la orden de apertura.', on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_conductor', to='control_vehicular.conductor')),
                ('persona', models.ForeignKey(help_text='Responsable de la orden de trabajo', on_delete=django.db.models.deletion.PROTECT, to='login.persona')),
                ('vehiculo', models.ForeignKey(help_text='El vehículo del cual se abre la orden de movimiento.', on_delete=django.db.models.deletion.PROTECT, to='control_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Apertura de orden de movimiento',
                'verbose_name_plural': 'Aperturas de órdenes de movimiento',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now=True, help_text='Fecha de emisión de la orden de trabajo')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO_CONSERVATIVO', 'Preventivo conservativo'), ('PREVENTIVO_PREDICTIVO', 'Preventivo predictivo'), ('CORRECTIVO', 'Correctivo'), ('RESTAURATIVO', 'Restaurativo')], help_text='Tipo de mantenimiento a realizar', max_length=30)),
                ('tipo_trabajo', models.TextField(help_text='Descripción del trabajo a realizar')),
                ('cumplimiento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDO', 'Cumplido')], help_text='Estado de cumplimiento de la orden de trabajo', max_length=20)),
                ('persona', models.ForeignKey(help_text='Responsable de la orden de trabajo', on_delete=django.db.models.deletion.PROTECT, to='login.persona')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo asociado con la orden de trabajo', on_delete=django.db.models.deletion.PROTECT, to='control_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='CierreOrdenMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_cierre_orden', models.DateField(auto_now=True, help_text='Fecha del cierre de la orden de movimiento')),
                ('fecha_retorno_vehiculo', models.DateField(help_text='Fecha de retorno del vehículo')),
                ('kilometraje_retorno', models.IntegerField(help_text='Kilometraje del vehículo al momento del retorno')),
                ('cumplimiento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDO', 'Cumplido')], help_text='Estado de cumplimiento de la orden de movimiento', max_length=20)),
                ('apertura', models.OneToOneField(help_text='Apertura de la orden de movimiento a la que se vincula el cierre de la misma', on_delete=django.db.models.deletion.PROTECT, to='operaciones.aperturaordenmovimiento')),
            ],
            options={
                'verbose_name': 'Cierre de orden de movimiento',
                'verbose_name_plural': 'Cierres de órdenes de movimiento',
            },
        ),
    ]
