# Generated by Django 4.2.1 on 2023-06-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_cierreordenmovimiento_apertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaordenmovimiento',
            name='responsable',
            field=models.ForeignKey(default=1, help_text='Responsable de la orden de trabajo', on_delete=django.db.models.deletion.PROTECT, to='operaciones.responsable'),
            preserve_default=False,
        ),
    ]
