# Generated by Django 4.2.1 on 2023-06-14 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial de la empresa.', max_length=255, verbose_name='Nombre comercial')),
                ('ruc', models.CharField(help_text='RUC de la empresa.', max_length=13, verbose_name='RUC')),
                ('direccion', models.CharField(help_text='Dirección de la empresa.', max_length=200, verbose_name='Dirección')),
                ('correo', models.EmailField(help_text='Correo electrónico de la empresa.', max_length=100, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(help_text='Teléfono de la empresa.', max_length=15, validators=[login.models.validar_numero_de_telefono], verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la funcionalidad.', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(help_text='Descripción de la funcionalidad.', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Funcionalidad',
                'verbose_name_plural': 'Funcionalidades',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.persona')),
                ('ruc', models.CharField(help_text='RUC del representante.', max_length=13, verbose_name='RUC')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
            bases=('login.persona',),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.persona')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que está asociado el trabajador.', on_delete=django.db.models.deletion.PROTECT, to='suscripciones.empresa')),
            ],
            bases=('login.persona',),
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo de suscripción.', max_length=255, verbose_name='Tipo')),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la suscripción', verbose_name='Fecha emisión')),
                ('duracion', models.IntegerField(help_text='Duración de la suscripción en días.', verbose_name='Duración')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la suscripción.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funcionalidades', models.ManyToManyField(help_text='Funcionalidades de la suscripción.', to='suscripciones.funcionalidad')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante_legal',
            field=models.OneToOneField(help_text='Representante legal de la empresa.', on_delete=django.db.models.deletion.CASCADE, to='suscripciones.representante'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='suscripcion',
            field=models.OneToOneField(help_text='Suscripción de la empresa.', on_delete=django.db.models.deletion.CASCADE, to='suscripciones.subscripcion'),
        ),
    ]
