@startuml suscripciones

' Patrón de diseño: Strategy

skinparam style strict

interface SubscriptionStrategy {
    + getFeatures(): List<String>
}

class BasicSubscriptionStrategy {
    + getFeatures(): List<String>
}

class CustomSubscriptionStrategy {
    + getFeatures(): List<String>
}

class PremiumSubscriptionStrategy {
    + getFeatures(): List<String>
}

class Company {
    - strategy: SubscriptionStrategy
    - duration: int
    + setStrategy(strategy: SubscriptionStrategy)
    + setDuration(duration: int)
    + getDuration(): int
    + getAvailableFeatures(): List<String>
}

Company -up-> "1" SubscriptionStrategy: <<use>>

BasicSubscriptionStrategy ..|> SubscriptionStrategy
CustomSubscriptionStrategy ..|> SubscriptionStrategy
PremiumSubscriptionStrategy ..|> SubscriptionStrategy


@enduml