# Generated by Django 4.2.1 on 2023-08-01 16:33

from django.db import migrations, models
import django.db.models.deletion
import usuarios.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la funcionalidad.', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(help_text='Descripción de la funcionalidad.', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Funcionalidad',
                'verbose_name_plural': 'Funcionalidades',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo de suscripción.', max_length=255, verbose_name='Tipo')),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la suscripción', verbose_name='Fecha emisión')),
                ('fecha_caducidad', models.DateField(help_text='Fecha de caducidad de la suscripción', verbose_name='Fecha de caducidad')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la suscripción', max_digits=10, verbose_name='Precio de la suscripción')),
                ('funcionalidades', models.ManyToManyField(help_text='Funcionalidades de la suscripción.', to='empresas.funcionalidad')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial de la empresa.', max_length=255, unique=True, verbose_name='Nombre comercial')),
                ('ruc', models.CharField(help_text='RUC de la empresa.', max_length=13, verbose_name='RUC')),
                ('direccion', models.TextField(help_text='Dirección de la empresa.', verbose_name='Dirección')),
                ('correo', models.EmailField(help_text='Correo electrónico de la empresa.', max_length=100, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(help_text='Teléfono de la empresa.', max_length=15, validators=[usuarios.validators.validar_numero_de_telefono], verbose_name='Teléfono')),
                ('logo_empresa', models.ImageField(blank=True, help_text='Logo de la empresa.', null=True, upload_to='', verbose_name='Logo de la empresa')),
                ('suscripcion', models.OneToOneField(help_text='Suscripción de la empresa.', on_delete=django.db.models.deletion.CASCADE, to='empresas.suscripcion')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
